[server]
address = "http://127.0.0.1:8080"

[crypto]
AESLength = 16
RSAPublicKeyPath ="./publicKey.pem"  

[collector]
searchPath = "./log"
filePath = '(\d{8})/gin.log'
parseTemplate = '^\[(?P<app>.+)\] {{date:/}} - {{time::}}\s+\|\s+(?P<status>\d{3})\s+\|\s+(?P<latency>\d+(\.\d+)?[a-zA-Z]+)\s+\|\s+{{ip}}\s+\|\s+(?P<request_method>[A-Z]+)\s+"(?P<request_path>.+)"$'
reportInterval = 1